### ISSUE TITLE
Missing an effect on the stars when playing above 720p

### ISSUE THREAD

**Issue by hyperspeedgx** [rebtd7/FF13Fix#19]
Another thing broken is the effect on stars that appear after you win battles (I think it's a bloom effect or something related to light) will be missing if you play above 720p.

I will post some images later showing it, hopefully you can fix it too, after the libra missing text issue, this is the most annoying issue atm.

**Comment by Surihix** [comment]
I have noticed the same issue just now after seeing your post. Weird how this went completely unnoticed by the steam community and real thnx for posting this issue here. 


Here r some images. the effect is available on all resolutions from 1280x720 to 1280x1024. It starts to go out of focus from 1360 resolution on wards and is completely missing on 1080p and higher resolution. 

this screenshot is taken when the game is in 1280x1024 resolution with the effect.
https://imgur.com/8RCvnq7
 
this is where the effect looks like an out of focus rectangle at 1360x768 which is just after the 1280 resolution set.
https://imgur.com/7jx27AJ

this is how it looks like at 1080p resolution and on higher resolution. the effect is completely gone.
https://imgur.com/M1c5ErQ


I have also noticed an issue with the effects that should appear behind textboxes in the game. there is an effect behind every text box where all of tht is out of focus and is completely missing at higher than 720p and 1080p resolutions. Here are the screenshots at different resolutions. 

this set of screenshot r taken when the game ran at 1280x1024 resolution with the effect in place. Notice tht globe like effect and the spinning gears effect in the boxes.
https://imgur.com/o2HVhbo
https://imgur.com/Jn9VQwr
https://imgur.com/VTUccWm
https://imgur.com/yzKANCX

this set of screenshot r taken when the game ran at 1366x768 resolution with the effect slightly misaligned.
https://imgur.com/0yQW8Sl
https://imgur.com/JEoflCX
https://imgur.com/xLZ4Se0
https://imgur.com/vGm39oo

this set of screenshots r taken when the game ran at 1920x1080 resolution with the effect missing.
https://imgur.com/cFg02DX
https://imgur.com/LkBTwlp
https://imgur.com/Ikei5sh
https://imgur.com/Um6c4tX

These effects r also present in most textboxes like the ones I posted here and I think these two issues r similar to the enemy intel bug. I am really hoping you can solve these issues with an update of sorts to the fix.

**Comment by rebtd7** [comment]
very interesting find, thanks you both. I'll take a look eventually.

**Comment by rebtd7** [comment]
Fixed in 1.4.5 (hopefully without breaking anything else).

**Comment by rebtd7** [comment]
Re-opening for now (see comments on issue #20)
