### ISSUE TITLE
Not working with Proton on Linux

### ISSUE THREAD

**Issue by pedrofleck** [rebtd7/FF13Fix#6]
Hi,
I know you don't support Linux, but maybe you can see if this is a problem with Wine (the compatibility layer between Linux and Windows software that powers [Proton](https://github.com/ValveSoftware/Proton)) libraries or if it is a problem that would happen on Windows too (in this case you could help me). The fix isn't working (I'm having the same problems with framerate), here is the log:

> [TIME]		[THREAD]	[LOG]
17:19:16.245	00000054	FF13Fix 1.4.1 https://github.com/rebtd7/FF13Fix
17:19:16.245	00000054	AutoFix for "Final Fantasy XIII" enabled
17:19:16.245	00000054	Base Addr = 400000
17:19:16.245	00000054	Loaded C:\windows\system32\d3d9.dll
17:19:16.459	00000054	HWND 0x00020054: ClassName "OleMainThreadWndClass", WindowName: ""
17:19:16.764	00000054	hkIDirect3D9::GetAdapterIdentifier
17:19:16.815	00000054	HWND 0x0002004E: ClassName "IME", WindowName: "Default IME"
17:19:16.815	00000054	HWND 0x0003004A: ClassName "WineD3D_OpenGL", WindowName: "WineD3D fake window"
17:19:16.936	00000054	HWND 0x00030056: ClassName "IME", WindowName: "Default IME"
17:19:16.936	00000054	HWND 0x0004004A: ClassName "DirectDrawDeviceWnd", WindowName: "Hidden D3D Window"
17:19:16.942	00000054	hkIDirect3D9::Release
17:19:17.134	00000054	HWND 0x00020058: ClassName "IME", WindowName: "Default IME"
17:19:17.134	00000054	HWND 0x0003004E: ClassName "Static", WindowName: "test"
17:19:17.148	00000054	hkIDirect3D9::CreateDevice
17:19:17.148	00000054	BehaviorFlags: 00000056 D3DCREATE_FPU_PRESERVE D3DCREATE_HARDWARE_VERTEXPROCESSING D3DCREATE_MULTITHREADED D3DCREATE_PUREDEVICE
17:19:17.148	00000054	BackBufferCount: BackBufferCount set to 3
17:19:17.148	00000054	PresentationInterval: PresentationInterval set to 1
17:19:17.193	00000054	hkIDirect3D9::Release
17:19:17.196	00000054	HWND 0x0004004E: ClassName "IME", WindowName: "Default IME"
17:19:17.197	00000054	HWND 0x00030054: ClassName "SQEX.CDev.Engine.Framework.MainWindow", WindowName: ""
17:19:17.215	00000054	hkIDirect3D9::CreateDevice
17:19:17.215	00000054	BehaviorFlags: 00000056 D3DCREATE_FPU_PRESERVE D3DCREATE_HARDWARE_VERTEXPROCESSING D3DCREATE_MULTITHREADED D3DCREATE_PUREDEVICE
17:19:17.215	00000054	BackBufferCount: BackBufferCount set to 3
17:19:17.215	00000054	Changing refresh rate from 60 to 0
17:19:17.215	00000054	PresentationInterval: PresentationInterval set to 1
17:19:17.372	00000071	Loaded C:\windows\system32\dinput8.dll
17:19:28.362	00000054	HWND 0x00020084: ClassName "Message", WindowName: ""
17:21:54.359	00000054	HWND 0x00020086: ClassName "Message", WindowName: ""
17:21:54.360	00000054	HWND 0x00020082: ClassName "#32770", WindowName: ""
17:21:54.361	00000054	HWND 0x0002007C: ClassName "Static", WindowName: ""
17:21:54.361	00000054	HWND 0x00020078: ClassName "Button", WindowName: "&Sim"
17:21:54.361	00000054	HWND 0x0002007A: ClassName "Button", WindowName: "&Não"
17:21:54.361	00000054	HWND 0x00020076: ClassName "Button", WindowName: "&Abortar"
17:21:54.362	00000054	HWND 0x00020072: ClassName "Button", WindowName: "&Repetir"
17:21:54.362	00000054	HWND 0x00020074: ClassName "Button", WindowName: "OK"
17:21:54.362	00000054	HWND 0x00020070: ClassName "Button", WindowName: "Cancelar"
17:21:54.363	00000054	HWND 0x0002006C: ClassName "Button", WindowName: "&Ignorar"
17:21:54.363	00000054	HWND 0x0002006E: ClassName "Button", WindowName: "&Tente Novamente"
17:21:54.363	00000054	HWND 0x0002006A: ClassName "Button", WindowName: "&Continuar"
17:21:54.364	00000054	HWND 0x00020068: ClassName "Button", WindowName: "Ajuda"
17:21:54.364	00000054	HWND 0x00020066: ClassName "Static", WindowName: ""
17:21:54.393	00000054	HWND 0x00030084: ClassName "Message", WindowName: ""
17:21:55.340	00000054	HWND 0x00030082: ClassName "Message", WindowName: ""
17:21:55.502	00000054	Unloaded C:\windows\system32\dinput8.dll
17:21:55.502	00000054	Unloaded C:\windows\system32\d3d9.dll

**Comment by Nucleoprotein** [comment]
I dont think you can run this on Wine. This fix is using API hooking and memory patching, both can have a problems when run on Wine because memroy structures can be different or some API missing/unsupported or cant be hooked because API function prolog can be to short or incompatible.

@rebtd7 
Can you add some printlog to error codes here? https://github.com/rebtd7/FF13Fix/blob/98ed61b776dc106bb08c704518d8381173322844/d3d9ex/Context.cpp#L49
And to all MH_CreateHook/MH_EnableHook, all function return MH_STATUS:
https://github.com/rebtd7/FF13Fix/blob/98ed61b776dc106bb08c704518d8381173322844/MinHook/include/MinHook.h#L38

**Comment by rebtd7** [comment]
@Nucleoprotein Thanks for also checking this. I'll add the extra logs and release a new version with them, as it may help fixing not only this issue, but possibly others. It is possible that for this specific issue the hooking is actually working fine though, maybe just the memory patches are failing

@pedrofleck Could you try version 1.3.1? https://github.com/rebtd7/FF13Fix/releases/tag/v1.3.1

The releases after this version only patch the memory for FFXIII when the window DIEmWin is created :
https://github.com/rebtd7/FF13Fix/blob/98ed61b776dc106bb08c704518d8381173322844/d3d9ex/Context.cpp#L183

And I see no such window being created in your log. If this does fix your issue I'll have to use something else to trigger the patches.

**Comment by rebtd7** [comment]
I've tried it on Proton 4.11-12 and it worked fine (using FF13Fix 1.4.1).
For some reason I had to open it multiple times to get my controller working, but I'm not sure if this is related to FF13Fix. The only thing that did not seem to work was the vibration support.

I've used the following launch parameters (taken from https://www.protondb.com/app/292120):
```
WINEARCH=win32 PROTON_FORCE_LARGE_ADDRESS_AWARE=1 PROTON_USE_D9VK=1 PROTON_USE_WINED3D=1 %command%
```

and I added the following to the DLLOverrides part of $HOME/.steam/steam/steamapps/compatdata/292120/pfx
```
"dinput8"="native,builtin"
```

**Comment by Nucleoprotein** [comment]
Vibration support is written for XInput, not for DirectInput

**Comment by rebtd7** [comment]
Please try 1.4.3 and report back (see issue #8)

**Comment by wjoe** [comment]
Thanks for the tips - I needed to add the dinput8 override with winecfg to get it working. I've just tried with the latest 1.4.3 and can confirm it's mostly working under Proton - framerate is significantly improved, up to 50+ FPS in Gran Pulse compared to ~30 FPS before. As you said, controller vibration doesn't work but this doesn't really surprise me, it's fairly rare for that to ever work under Wine/Proton.

**Comment by thatcosmonaut** [comment]
Just gonna post in here because I just had an adventure getting this game running. Here's how I did it:

- Install FF13Fix normally.
- Run WINEARCH=win32 winecfg and add dinput8 to DLLOverrides
- Steam launch options: WINEARCH=win32 PROTON_FORCE_LARGE_ADDRESS_AWARE=1 taskset -c 0-3 %command%

Game runs normally with smooth framerate now.

DO NOT USE WINE_D3D because this breaks the game's internal anti-aliasing and leads to several graphics glitches. In latest Proton (5.0.5 as of this writing) DXVK is set by default. 

Runs great now aside from occasional stuttering that I assume is a result of d9vk shader compilation. I couldn't even get the game to start on Windows so that's a big improvement!

**Comment by danilo-bc** [comment]
I'm also here to attest to being able to use the fix on Proton on Fedora Linux. This issue can be closed.

Also, there's no need to use "taskset" at the moment. I found out that, with weaker CPUs, taskset causes audio crackling issues (because you're getting CPU bottlenecks all around). With this fix, you can safely disable that measure (which works great WITHOUT the fix). I'm running on a mobile i7 and the extra threads help a lot mitigating these issues.

If you want to use the newer 1.5.x versions, simply add d3d9 to your DLL overrides with `protontricks 292120 winecfg`, the same way as you would add dinput8 as an override (remember to take this one out if you're using 1.5.x)

**Comment by rebtd7** [comment]
Closing as it seems to work fine in Proton and OP never replied.
