### ISSUE TITLE
Random Battle Freezes

### ISSUE THREAD

**Issue by Unrul3r** [rebtd7/FF13Fix#7]
It's not directly related to this fix so I'm not sure if you can do anything about it but it seems there's a freezing issue that happens to 5700 series users. Some say its the AMD drivers. The game basically locks-up in random fights and produces a buzzing sound until it's forced to close.

It seems its only during fights. I have a specific spot which I can more or less reliably cause it to occur. Not always but it triggers within 4 tries.

There's more info on both of these threads that describe it:
https://steamcommunity.com/app/292120/discussions/0/1635292137565553166/
https://steamcommunity.com/app/292120/discussions/0/1752394282893142693/

Is there anything we can do about this?

**Comment by Nucleoprotein** [comment]
The latest drivers not fix that? AMD fixed many bugs silently in latest
drivers:
https://www.google.com/amp/s/www.techpowerup.com/263237/amd-quietly-patched-four-major-gpu-security-vulnerabilities-with-radeon-20-1-1-drivers%3famp

niedz., 2 lut 2020, 23:36 użytkownik Unrul3r <notifications@github.com>
napisał:

**Comment by Unrul3r** [comment]
Apparently not everything is fixed. I'm at the latest version 20.1.4. Going to try the 19.12.1 drivers to see if it changes anything.

**Comment by rebtd7** [comment]
I suggest reporting the issue to AMD (it seems you can provide feedback on their driver) and trying visibility to the problem (perhaps posting on AMD's subreddit). I think it is the best change of solving the issue.

It seems they list a crash in Final Fantasy XIV: Shadowbringers benchmark in their driver release notes. I wonder if it has something to do with the crashes in this game (maybe FF14 also uses a variant of the same engine?)

As a workaround you can also try using a Vulkan wrapper like suggested on those threads, and maybe even trying Proton on Linux (you'll probably have extra stuttering with either due to the API conversions though)

You could also try using [apitrace](http://apitrace.github.io/) to see if it always crashes on an specific API call

e.g.:
apitrace.exe trace -a d3d9 -o ff13_amd_crash_attempt_1.trace ffxiiiimg.exe

then opening the trace with qapitrace and checking the last command of the last frame after every crash.

Even if it does, I'm not sure if we could use this to solve anything (and I'm very far from being an expert with Direct3D). AMD would probably be able to use that info though (but then again, they should be the ones looking into it)

**Comment by Unrul3r** [comment]
> I suggest reporting the issue to AMD (it seems you can provide feedback on their driver) and trying visibility to the problem (perhaps posting on AMD's subreddit). I think it is the best chance of solving the issue.

Yes, already did this.

> As a workaround you can also try using a Vulkan wrapper like suggested on those threads, and maybe even trying Proton on Linux (you'll probably have extra stuttering with either due to the API conversions though)

Also tried a bunch of wrappers, their performance is not great. They drop a lot of frames. Didn't try Proton on Linux though. Haven't bothered to dual-boot it on this PC yet.

> You could also try using [apitrace](http://apitrace.github.io/) to see if it always crashes on an specific API call
> 
> e.g.:
> apitrace.exe trace -a d3d9 -o ff13_amd_crash_attempt_1.trace ffxiiiimg.exe
> 
> then opening the trace with qapitrace and checking the last command of the last frame after every crash.
> 
> Even if it does, I'm not sure if we could use this to solve anything (and I'm very far from being an expert with Direct3D). AMD would probably be able to use that info though (but then again, they should be the ones looking into it)

Thanks! This seems interesting. Going to try it.

**Comment by Unrul3r** [comment]
Ok. So I've got a trace. It caught an unhandled exception 4 frames before the end of the trace.

Debug Type
`97318679 @0 IDirect3DDevice9::SetStreamSource(this = 0xf074998, StreamNumber = 0, pStreamData = 0x5cddb160, OffsetInBytes = 0, Stride = 28) = D3D_OK`

Error Type
`97318694 @0 IDirect3DDevice9::SetStreamSourceFreq(this = 0xf074998, StreamNumber = 7, Setting = 1) = D3D_OK`

Don't know what any of this means. 😆

**Comment by Unrul3r** [comment]
So, I've got the trace. I experimented a bit with the GUI do read the trace but I'm unsure how to go forward. I found unhandled exceptions when I tried to replay the trace but they appear in different places every time I replay it. How do I look for the problem if it's indeed to be found in the API?

**Comment by rebtd7** [comment]
> 
> 
> ~So, I've got the trace. I experimented a bit with the GUI to read the trace but I'm unsure how to go forward. I found unhandled exceptions when I tried to replay the trace but they appear in different places every time I replay it. How do I look for the problem if it's indeed to be found in the API?~
> 
> Edit: The crash still happens in drivers 19.12.1.
> Edit2: Back to using my old RX 580.

My idea was to simply crash a bunch of times and check if the very last API logged by apitrace is the same.

Things like this (worst stability overall, bugged drivers, abysmal OpenGL perfomance) is the reason why I don't buy AMD GPUs

I'll close this issue for now. I wish I could fix this, but it very hard to do anything about it (especially without having the capability to reproduce the issue and using a substantial amount of time). If anyone else wants to give it a go, please do so (the project is open source after all)
