### ISSUE TITLE
Performance regression since version 1.4.0.

### ISSUE THREAD

**Issue by ke5koB** [rebtd7/FF13Fix#8]
Hello! Thank you for your work.
I noticed that the performance FF 13 in heavy scenes is much lower (from 60 ~ 55 to 30 ~ 35 fps) in comparison with 1.3.1.
turning off the vibration gives the same result.
spec 
win7 x64
i5 2500k
gtx 1060
xinput controller

**Comment by rebtd7** [comment]
I'm assuming you are playing FF13 and not FF13-2.

The biggest change is that now the patches are only applied when a window called "DIEmWin" is opened instead of trying to apply them every where.

Could you post a log using the latest version? Is there anywhere you can reproduce the performance regression? Could you post a save near that point?

**Comment by Nucleoprotein** [comment]
Thats not correct game window, "DIEmWin" is created by "NVIDIA Game Proxy" - part of NVIDIA drivers, so if he not have NV card now this fix will not work for him.
Main game windows seems to be:
`15:47:09.621	00006196	HWND 0x000809F6: ClassName "SQEX.CDev.Engine.Framework.MainWindow", WindowName: ""`

**Comment by rebtd7** [comment]
@Nucleoprotein 
I'll see if this window is okay to use, but I had chosen that other one because of its timing (some of the patches can't be applied too early). And I remember having a difference between the windows opened on Windowed and Fullscreen mode. He is using a Nvidia card too.

Is it really broken for all AMD cards at the moment? I wonder why there hasn't been more people complaining about it

**Comment by rebtd7** [comment]
Please do post a log using both 1.4.2 and 1.4.3. 

Version 1.4.3 should hopefully fix your issue.

I hate relying on timing, but the solution I'm using for now is to wait a while before applying the RAM patches. 100ms seemed to be enough after the creation of the "SQEX.CDev.Engine.Framework.MainWindow" window, but I'm waiting 2000ms to be extra safe.

**Comment by ke5koB** [comment]
1.4.3 fix it for me. Thank you!  I also found that if i set compatibility with win xp sp3 then 1.4.2 also works fine, so maybe there is some problem with my system.
[logs.zip](https://github.com/rebtd7/FF13Fix/files/4175385/logs.zip)

**Comment by rebtd7** [comment]
Your file named "FF13Fix 1.4.3 log.log" is actually from version 1.4.2 btw. Please make sure you are using 1.4.3.

From your logs it seems that the window DIEmWin is being created anyway, so maybe it is merely a timing issue (perhaps the time that the window DIEmWin opens is too soon on some systems and the new version fixed this)

Feel free to re-open if you are still having this issue.
